apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keyhole-demo-bucket
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default  
  source:
    directory:
      jsonnet: {}
      recurse: true 
    path: apps/keyhole-demo-bucket
    repoURL: git@github.com:in-the-keyhole/keyhole-gitops.git
    targetRevision: HEAD
  syncPolicy: 
    automated:
      prune: true