apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-secret
  namespace: upbound-system
spec:
  encryptedData:
    creds: AgA6qG9/c9ugcJB8gFepezD5vWZ4dY5WcIAxd7vHXWZDerG68msWLdjoQG5AAVP67FCRp2m1odhUeRawUU2x8VsEuhXU4NIdIYwPttpnSlajH2Bdfhp6IHwiTxaGwkyD0IMGE2w+wbQ38xsBQYfw0g0p+HLaXiULoLh4LfVrTNUTZ6qwpMUBInH3QMIJ4S+Lxt8MaMR7t6+Ue7gNIpq4SFMw89RepC33VJwBjS9Xt8N96YQZUm8ssG0EKVb60ZFBQdTlANJSykZvn443Q0cjbbT3Ld+nH+gsll5FhSqx3CcQgATiNu8tB03VcO+xJ5UpguqgSFNLlJ3DESFAxu8aSCArE7bYXEcZa6WPzmuo0rWRuFDPfCUQaVDKf/8ZtzTOiJUgJhna61la7dzUmCdbtZb7yg2LzrY76Wk35009CWeNB475bv+WT8TARJ3e1Ye3ZEv4PCgHg4gH4aOaVxc120nMC0WhDhQ3tn5DXBPxv5jcn5CQmtTD/6cl2New+fxtMOL0FwL3GK0tixb12p9ls5PBu9ayBCnotvBTwWqpJ09j3WNoFjmMJi8GdukhcqwBTYNaXuqTjgvi506kjnM/qXIVhsToTWflaGm6L3TPbqIhIQy3GkUfggg487JRmqBcuFH6kfhSmbaBWvG0z+BqKW7ZAd0CVOOXQ3tZMzPC9Lyxb293frw3/H+xac3nt6ZnIq1vAiEBLRDq2/P5gWQDYhetN62Hrw6al05FqLsW9ZjD0Xs/hZHBx8rfqPOEOZ2rujucq9xiGBK+KIs8Rv36K06pFr69rJrwCEkgiEQhlCEVOAb4nU3n5J0eZD3bckwRn+bUDr+IfBMZBSk3t+eMtEtIhrABSQ==
  template:
    metadata:
      name: aws-secret
      namespace: upbound-system
    type: Opaque

