apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-providers
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: providers
    repoURL: git@github.com:in-the-keyhole/keyhole-gitops.git
    targetRevision: HEAD