# 
# 

---
apiVersion: cloudfront.keyholesoftware.com/v1alpha1
kind: Distribution
metadata:
  namespace: default
  name: keyhole-demo
spec:
  parameters:
    region: us-east-2
    dnsSuffix: keyhole.institute
  compositionRef:
    name: cloudfront-distribution