

---
apiVersion: cloudfront.aws.upbound.io/v1beta1
kind: Distribution
metadata:
  annotations:
    # meta.upbound.io/example-id: cloudfront/v1beta1/distribution
  labels:
    # testing.upbound.io/example-name: keyhole-demo-dev
    testing.upbound.io/example-name: keyhole-demo-dev
  # name: keyhole-demo-dev
  name: keyhole-demo-dev
spec:
  forProvider:
    aliases:
    - keyhole-demo-dev.keyhole.institute
    # - yoursite.example.com
    comment: 
    defaultCacheBehavior:
    - allowedMethods:
      - DELETE
      - GET
      - HEAD
      - OPTIONS
      - PATCH
      - POST
      - PUT
      cachedMethods:
      - GET
      - HEAD
      defaultTtl: 3600
      forwardedValues:
      - cookies:
        - forward: none
        queryString: false
      maxTtl: 86400
      minTtl: 0
      targetOriginId: s3_origin
      viewerProtocolPolicy: redirect-to-https
      compress: true
    defaultRootObject: index.html
    enabled: true
    isIpv6Enabled: true
    # loggingConfig:
    # - bucket: mylogs.s3.amazonaws.com
    #   includeCookies: false
    #   prefix: myprefix
    # orderedCacheBehavior:
    # - allowedMethods:
    #   - GET
    #   - HEAD
    #   - OPTIONS
    #   cachedMethods:
    #   - GET
    #   - HEAD
    #   - OPTIONS
    #   compress: true
    #   defaultTtl: 86400
    #   forwardedValues:
    #   - cookies:
    #     - forward: none
    #     headers:
    #     - Origin
    #     queryString: false
    #   maxTtl: 31536000
    #   minTtl: 0
    #   pathPattern: /content/immutable/*
    #   targetOriginId: ${local.s3_origin_id}
    #   viewerProtocolPolicy: redirect-to-https
    # - allowedMethods:
    #   - GET
    #   - HEAD
    #   - OPTIONS
    #   cachedMethods:
    #   - GET
    #   - HEAD
    #   compress: true
    #   defaultTtl: 3600
    #   forwardedValues:
    #   - cookies:
    #     - forward: none
    #     queryString: false
    #   maxTtl: 86400
    #   minTtl: 0
    #   pathPattern: /content/*
    #   targetOriginId: ${local.s3_origin_id}
    #   viewerProtocolPolicy: redirect-to-https
    origin:
    # - domainName: ${aws_s3_bucket.crossplane-example.bucket_regional_domain_name}
    # - domainName: keyhole-demo-dev.s3-website.us-east-2.amazonaws.com
    - domainName: keyhole-demo-dev-841.s3-website.us-east-2.amazonaws.com
      # originAccessControlId: ${aws_cloudfront_origin_access_control.default.id}
      # originId: ${local.s3_origin_id}
      originId: s3_origin
      customOriginConfig:
      - httpPort: 80
        httpsPort: 443
        originProtocolPolicy: http-only
        originSslProtocols:
          - TLSv1
          - TLSv1.1
          - TLSv1.2
    priceClass: PriceClass_100
    region: us-east-2
    restrictions:
    - geoRestriction:
      - locations:
        - US
        - CA
        - GB
        - DE
        restrictionType: whitelist
    tags:
      Environment: development
    viewerCertificate:
    # - cloudfrontDefaultCertificate: true
    - cloudfrontDefaultCertificate: false
      acmCertificateArn: arn:aws:acm:us-east-1:999330780379:certificate/95bc1cd7-4d73-4499-9a64-8f883d551c56

---

apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    # crossplane.io/external-name: ${Rand.RFC1123Subdomain}
    # meta.upbound.io/example-id: cloudfront/v1beta1/distribution
  labels:
    # testing.upbound.io/example-name: keyhole-demo-dev
    testing.upbound.io/example-name: keyhole-demo-dev
  # name: keyhole-demo-dev-462 
  name: keyhole-demo-dev-841
spec:
  forProvider:
    region: us-east-2
    tags:
      # Name: keyhole-demo-dev
      Name: keyhole-demo-dev

---

apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketWebsiteConfiguration
metadata:
  # name: keyhole-demo
  name: keyhole-demo-dev
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        # testing.upbound.io/example-name: keyhole-demo-dev
        testing.upbound.io/example-name: keyhole-demo-dev
    errorDocument:
      - key: error.html
    indexDocument:
      - suffix: index.html
    region: us-east-2
    # routingRule:
    #   - condition:
    #       - keyPrefixEquals: docs/
    #     redirect:
    #       - replaceKeyPrefixWith: documents/

---

apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketPolicy
metadata:
  annotations:
    # meta.upbound.io/example-id: s3/v1beta1/bucketpolicy
  labels:
    # testing.upbound.io/example-name: keyhole-demo-dev-bucket-policy
    testing.upbound.io/example-name: keyhole-demo-dev-bucket-policy
  # name: keyhole-demo-dev-bucket-policy
  name: keyhole-demo-dev-bucket-policy
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        # testing.upbound.io/example-name: keyhole-demo-dev
        testing.upbound.io/example-name: keyhole-demo-dev
    policy: >
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Sid": "PublicReadGetObject",
                  "Effect": "Allow",
                  "Principal": "*",
                  "Action": "s3:GetObject",
                  "Resource": "arn:aws:s3:::keyhole-demo-dev-841/*"
              }
          ]
      }
    region: us-east-2

---

# apiVersion: s3.aws.upbound.io/v1beta1
# kind: BucketACL
# metadata:
#   annotations:
#     meta.upbound.io/example-id: cloudfront/v1beta1/distribution
#   labels:
#     testing.upbound.io/example-name: crossplane-example-acl
#   name: crossplane-example-acl
# spec:
#   forProvider:
#     bucketSelector:
#       matchLabels:
#         testing.upbound.io/example-name: crossplane-example
#     region: us-east-2

# ---

